language: go

go:
  - 1.4.2

install:
  - go get golang.org/x/tools/cmd/vet
  - go get -v golang.org/x/lint/golint
  - go get -d -t -v ./...
  - go build -v ./...

script:
  - go vet ./...
  - $HOME/gopath/bin/golint ./...
  - go test -v -parallel=8 ./...
